#
# Docker file for metadata validation for Intan RHX
#
FROM debian:testing

# prepare
RUN mkdir -p /build/ci/

RUN apt-get -q update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -yq \
	appstream

# finish
WORKDIR /build
